FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Ajoute  app au PYTHONPATH
ENV PYTHONPATH="${PYTHONPATH}:/app"

EXPOSE 8000

CMD ["python", "app/app.py"]  # Pointe vers app/app.py
